/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author riden1862
 */
public class MultipleChoiceQuizGUI extends javax.swing.JFrame {

    /**
     * Creates new form MultipleChoiceQuizGUI
     */
    public MultipleChoiceQuizGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        lblQuestion1 = new javax.swing.JLabel();
        lblQuestion2 = new javax.swing.JLabel();
        lblQuestion3 = new javax.swing.JLabel();
        lblQuestion4 = new javax.swing.JLabel();
        lblQuestion5 = new javax.swing.JLabel();
        lblQ1a = new javax.swing.JLabel();
        lblQ1b = new javax.swing.JLabel();
        lblQ1c = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblQ2a = new javax.swing.JLabel();
        lblQ2c = new javax.swing.JLabel();
        lblQ2b = new javax.swing.JLabel();
        lblQ2d = new javax.swing.JLabel();
        lblQ3a = new javax.swing.JLabel();
        lblQ3b = new javax.swing.JLabel();
        lblQ3c = new javax.swing.JLabel();
        lblQ3d = new javax.swing.JLabel();
        lblQ4a = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtQ1answer = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQ2answer = new javax.swing.JTextField();
        txtQ3answer = new javax.swing.JTextField();
        txtQ4answer = new javax.swing.JTextField();
        txtQ5answer = new javax.swing.JTextField();
        lblQ1answer = new javax.swing.JLabel();
        lblQ2answer = new javax.swing.JLabel();
        lblQ3answer = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblQ5answer = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblHeader.setText("Multiple Choice Quiz");

        lblSubtitle.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSubtitle.setText("Horses Edition");

        lblQuestion1.setText("At what age is a horse described as having a 'full' mouth?");

        lblQuestion2.setText("What is the groove that appears on the upper corner incisor?");

        lblQuestion3.setText("How many footfalls/beats are in the rein back?");

        lblQuestion4.setText("What is an equine whose height is under the height of 14.2hh called?");

        lblQuestion5.setText("What is the most proper name used to call the person who puts their shoes on?");

        lblQ1a.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ1a.setText("a)  3");

        lblQ1b.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ1b.setText("b) 5");

        lblQ1c.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ1c.setText("c) 10");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel1.setText("d) 22");

        lblQ2a.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ2a.setText("a) Albeit's Groove");

        lblQ2c.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ2c.setText("c) Respon's Groove");

        lblQ2b.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ2b.setText("b) Galvanyne's Groove");

        lblQ2d.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ2d.setText("d) Mendel's Grove");

        lblQ3a.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ3a.setText("a) 3");

        lblQ3b.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ3b.setText("b) 2");

        lblQ3c.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ3c.setText("c) 4");

        lblQ3d.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ3d.setText("d) 1");

        lblQ4a.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ4a.setText("a) Miniture Horse");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel2.setText("b) Pony");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel3.setText("c) Horse");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel4.setText("d) Welsh");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel5.setText("a) Shoer");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel6.setText("b) Farrier");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel7.setText("c) Smith");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel8.setText("d) Shoemaker");

        txtQ1answer.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        txtQ1answer.setText("ans");
        txtQ1answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ1answerActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel9.setText("Enter your answer into the text fields below! Example, enter a");

        txtQ2answer.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        txtQ2answer.setText("ans");
        txtQ2answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ2answerActionPerformed(evt);
            }
        });

        txtQ3answer.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        txtQ3answer.setText("ans");
        txtQ3answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ3answerActionPerformed(evt);
            }
        });

        txtQ4answer.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        txtQ4answer.setText("ans");
        txtQ4answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ4answerActionPerformed(evt);
            }
        });

        txtQ5answer.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        txtQ5answer.setText("ans");
        txtQ5answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ5answerActionPerformed(evt);
            }
        });

        lblQ1answer.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ1answer.setText("right");

        lblQ2answer.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ2answer.setText("right");

        lblQ3answer.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ3answer.setText("right");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel10.setText("right");

        lblQ5answer.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ5answer.setText("right");

        btnSubmit.setText("Submit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblQuestion2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblQuestion3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblQuestion4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(lblSubtitle)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblQ3a)
                                .addGap(54, 54, 54)
                                .addComponent(lblQ3b)
                                .addGap(39, 39, 39)
                                .addComponent(lblQ3c)
                                .addGap(26, 26, 26)
                                .addComponent(lblQ3d)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtQ3answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblQ4a)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4))
                                    .addComponent(lblQuestion5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 7, Short.MAX_VALUE)
                                                .addComponent(lblQuestion1)
                                                .addGap(32, 32, 32))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblQ2a)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblQ2b)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblQ2c))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblQ1a, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(27, 27, 27)
                                                        .addComponent(lblQ1b)
                                                        .addGap(51, 51, 51)
                                                        .addComponent(lblQ1c)
                                                        .addGap(39, 39, 39)
                                                        .addComponent(jLabel1)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(lblQ2d)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtQ2answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQ4answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQ1answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel6)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel7)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtQ5answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQ1answer)
                            .addComponent(lblQ2answer)
                            .addComponent(lblQ3answer)
                            .addComponent(jLabel10)
                            .addComponent(lblQ5answer)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(lblHeader)))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(241, 241, 241))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lblSubtitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuestion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ1a)
                    .addComponent(lblQ1b)
                    .addComponent(lblQ1c)
                    .addComponent(jLabel1)
                    .addComponent(txtQ1answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ1answer))
                .addGap(14, 14, 14)
                .addComponent(lblQuestion2)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ2a)
                    .addComponent(lblQ2b)
                    .addComponent(lblQ2d)
                    .addComponent(lblQ2c)
                    .addComponent(txtQ2answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ2answer))
                .addGap(18, 18, 18)
                .addComponent(lblQuestion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ3a)
                    .addComponent(lblQ3b)
                    .addComponent(lblQ3c)
                    .addComponent(lblQ3d)
                    .addComponent(txtQ3answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ3answer))
                .addGap(14, 14, 14)
                .addComponent(lblQuestion4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ4a)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtQ4answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(12, 12, 12)
                .addComponent(lblQuestion5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtQ5answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ5answer))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQ1answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ1answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ1answerActionPerformed

    private void txtQ2answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ2answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ2answerActionPerformed

    private void txtQ3answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ3answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ3answerActionPerformed

    private void txtQ4answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ4answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ4answerActionPerformed

    private void txtQ5answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ5answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ5answerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultipleChoiceQuizGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblQ1a;
    private javax.swing.JLabel lblQ1answer;
    private javax.swing.JLabel lblQ1b;
    private javax.swing.JLabel lblQ1c;
    private javax.swing.JLabel lblQ2a;
    private javax.swing.JLabel lblQ2answer;
    private javax.swing.JLabel lblQ2b;
    private javax.swing.JLabel lblQ2c;
    private javax.swing.JLabel lblQ2d;
    private javax.swing.JLabel lblQ3a;
    private javax.swing.JLabel lblQ3answer;
    private javax.swing.JLabel lblQ3b;
    private javax.swing.JLabel lblQ3c;
    private javax.swing.JLabel lblQ3d;
    private javax.swing.JLabel lblQ4a;
    private javax.swing.JLabel lblQ5answer;
    private javax.swing.JLabel lblQuestion1;
    private javax.swing.JLabel lblQuestion2;
    private javax.swing.JLabel lblQuestion3;
    private javax.swing.JLabel lblQuestion4;
    private javax.swing.JLabel lblQuestion5;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JTextField txtQ1answer;
    private javax.swing.JTextField txtQ2answer;
    private javax.swing.JTextField txtQ3answer;
    private javax.swing.JTextField txtQ4answer;
    private javax.swing.JTextField txtQ5answer;
    // End of variables declaration//GEN-END:variables
}
