
import java.util.Scanner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author riden1862
 */
public class MultipleChoiceQuizGUI extends javax.swing.JFrame {

    /**
     * Creates new form MultipleChoiceQuizGUI
     */
    public MultipleChoiceQuizGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        lblQuestion1 = new javax.swing.JLabel();
        lblQuestion2 = new javax.swing.JLabel();
        lblQuestion3 = new javax.swing.JLabel();
        lblQuestion4 = new javax.swing.JLabel();
        lblQuestion5 = new javax.swing.JLabel();
        lblQ1a = new javax.swing.JLabel();
        lblQ1b = new javax.swing.JLabel();
        lblQ1c = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblQ2a = new javax.swing.JLabel();
        lblQ2c = new javax.swing.JLabel();
        lblQ2b = new javax.swing.JLabel();
        lblQ2d = new javax.swing.JLabel();
        lblQ3a = new javax.swing.JLabel();
        lblQ3b = new javax.swing.JLabel();
        lblQ3c = new javax.swing.JLabel();
        lblQ3d = new javax.swing.JLabel();
        lblQ4a = new javax.swing.JLabel();
        lblQ4b = new javax.swing.JLabel();
        lblQ4c = new javax.swing.JLabel();
        lblQ4d = new javax.swing.JLabel();
        lblQ5a = new javax.swing.JLabel();
        lblQ5b = new javax.swing.JLabel();
        lblQ5c = new javax.swing.JLabel();
        lblQ5d = new javax.swing.JLabel();
        txtQ1answer = new javax.swing.JTextField();
        lblUserPrompt = new javax.swing.JLabel();
        txtQ2answer = new javax.swing.JTextField();
        txtQ3answer = new javax.swing.JTextField();
        txtQ4answer = new javax.swing.JTextField();
        txtQ5answer = new javax.swing.JTextField();
        lblQ1answer = new javax.swing.JLabel();
        lblQ2answer = new javax.swing.JLabel();
        lblQ3answer = new javax.swing.JLabel();
        lblQ4answer = new javax.swing.JLabel();
        lblQ5answer = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        lblCorrectQuestions = new javax.swing.JLabel();
        lblTotalCorrect = new javax.swing.JLabel();
        lblNumQuestionsAnswered = new javax.swing.JLabel();
        questionsAnsweredTotal = new javax.swing.JLabel();
        lblIncorrectQuestions = new javax.swing.JLabel();
        lblTotalIncorrect = new javax.swing.JLabel();
        lblPercentCorrect = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblHeader.setText("Multiple Choice Quiz");

        lblSubtitle.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSubtitle.setText("Horses Edition");

        lblQuestion1.setText("At what age is a horse described as having a 'full' mouth?");

        lblQuestion2.setText("What is the groove that appears on the upper corner incisor?");

        lblQuestion3.setText("How many footfalls/beats are in the rein back?");

        lblQuestion4.setText("What is an equine whose height is under the height of 14.2hh called?");

        lblQuestion5.setText("What is the most proper name used to call the person who puts their shoes on?");

        lblQ1a.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ1a.setText("a)  3");

        lblQ1b.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ1b.setText("b) 5");

        lblQ1c.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ1c.setText("c) 10");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel1.setText("d) 22");

        lblQ2a.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ2a.setText("a) Albeit's Groove");

        lblQ2c.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ2c.setText("c) Respon's Groove");

        lblQ2b.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ2b.setText("b) Galvanyne's Groove");

        lblQ2d.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ2d.setText("d) Mendel's Grove");

        lblQ3a.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ3a.setText("a) 3");

        lblQ3b.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ3b.setText("b) 2");

        lblQ3c.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ3c.setText("c) 4");

        lblQ3d.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ3d.setText("d) 1");

        lblQ4a.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ4a.setText("a) Miniture Horse");

        lblQ4b.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ4b.setText("b) Pony");

        lblQ4c.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ4c.setText("c) Horse");

        lblQ4d.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ4d.setText("d) Welsh");

        lblQ5a.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ5a.setText("a) Shoer");

        lblQ5b.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ5b.setText("b) Farrier");

        lblQ5c.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ5c.setText("c) Smith");

        lblQ5d.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblQ5d.setText("d) Shoemaker");

        txtQ1answer.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        txtQ1answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ1answerActionPerformed(evt);
            }
        });

        lblUserPrompt.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblUserPrompt.setText("Enter your answer into the text fields below! Example, enter 'a'");

        txtQ2answer.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        txtQ2answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ2answerActionPerformed(evt);
            }
        });

        txtQ3answer.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        txtQ3answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ3answerActionPerformed(evt);
            }
        });

        txtQ4answer.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        txtQ4answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ4answerActionPerformed(evt);
            }
        });

        txtQ5answer.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        txtQ5answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ5answerActionPerformed(evt);
            }
        });

        lblQ1answer.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N

        lblQ2answer.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N

        lblQ3answer.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N

        lblQ4answer.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N

        lblQ5answer.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblCorrectQuestions.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblCorrectQuestions.setText("Correct Questions");

        lblTotalCorrect.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N

        lblNumQuestionsAnswered.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblNumQuestionsAnswered.setText("Questions Answered");

        questionsAnsweredTotal.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N

        lblIncorrectQuestions.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblIncorrectQuestions.setText("Incorrect Questions");

        lblTotalIncorrect.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N

        lblPercentCorrect.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblQuestion2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblQuestion3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblQuestion4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(lblSubtitle)
                        .addGap(26, 26, 26)
                        .addComponent(lblUserPrompt))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblQ4a)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblQ4b)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblQ4c)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblQ4d))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(0, 7, Short.MAX_VALUE)
                                            .addComponent(lblQuestion1)
                                            .addGap(32, 32, 32))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblQ2a)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(lblQ2b)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(lblQ2c))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(lblQ1a, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(27, 27, 27)
                                                    .addComponent(lblQ1b)
                                                    .addGap(51, 51, 51)
                                                    .addComponent(lblQ1c)
                                                    .addGap(39, 39, 39)
                                                    .addComponent(jLabel1)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(lblQ2d))
                                .addComponent(lblQuestion5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblQ3a)
                                .addGap(54, 54, 54)
                                .addComponent(lblQ3b)
                                .addGap(39, 39, 39)
                                .addComponent(lblQ3c)
                                .addGap(26, 26, 26)
                                .addComponent(lblQ3d))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblQ5a)
                                .addGap(37, 37, 37)
                                .addComponent(lblQ5b)
                                .addGap(41, 41, 41)
                                .addComponent(lblQ5c)
                                .addGap(29, 29, 29)
                                .addComponent(lblQ5d)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQ5answer, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                            .addComponent(txtQ3answer)
                            .addComponent(txtQ2answer)
                            .addComponent(txtQ4answer)
                            .addComponent(txtQ1answer))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQ1answer)
                            .addComponent(lblQ2answer)
                            .addComponent(lblQ3answer)
                            .addComponent(lblQ4answer)
                            .addComponent(lblQ5answer)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(lblHeader))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNumQuestionsAnswered)
                            .addComponent(lblCorrectQuestions)
                            .addComponent(lblIncorrectQuestions))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblTotalIncorrect)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(lblTotalCorrect))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(questionsAnsweredTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPercentCorrect)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSubmit)))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserPrompt)
                    .addComponent(lblSubtitle))
                .addGap(18, 18, 18)
                .addComponent(lblQuestion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ1a)
                    .addComponent(lblQ1b)
                    .addComponent(lblQ1c)
                    .addComponent(jLabel1)
                    .addComponent(txtQ1answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ1answer))
                .addGap(14, 14, 14)
                .addComponent(lblQuestion2)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ2a)
                    .addComponent(lblQ2b)
                    .addComponent(lblQ2d)
                    .addComponent(lblQ2c)
                    .addComponent(txtQ2answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ2answer))
                .addGap(18, 18, 18)
                .addComponent(lblQuestion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ3a)
                    .addComponent(lblQ3b)
                    .addComponent(lblQ3c)
                    .addComponent(lblQ3d)
                    .addComponent(txtQ3answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ3answer))
                .addGap(14, 14, 14)
                .addComponent(lblQuestion4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ4a)
                    .addComponent(lblQ4b)
                    .addComponent(lblQ4c)
                    .addComponent(lblQ4d)
                    .addComponent(txtQ4answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ4answer))
                .addGap(12, 12, 12)
                .addComponent(lblQuestion5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ5a)
                    .addComponent(lblQ5b)
                    .addComponent(lblQ5c)
                    .addComponent(lblQ5d)
                    .addComponent(txtQ5answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ5answer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorrectQuestions)
                            .addComponent(lblTotalCorrect)
                            .addComponent(lblPercentCorrect))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIncorrectQuestions)
                            .addComponent(lblTotalIncorrect))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSubmit)
                            .addComponent(lblNumQuestionsAnswered)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(questionsAnsweredTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQ1answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ1answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ1answerActionPerformed

    private void txtQ2answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ2answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ2answerActionPerformed

    private void txtQ3answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ3answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ3answerActionPerformed

    private void txtQ4answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ4answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ4answerActionPerformed

    private void txtQ5answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ5answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ5answerActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        //Scanner keyedInput = new Scanner(System.in);
        String ans1;
        String ans2;
        String ans3;
        String ans4;
        String ans5;
        int totalCorrect;
        totalCorrect = 0;
        int totalIncorrect;
        totalIncorrect = 0;
        int numQuestionsAnswered;
        numQuestionsAnswered = 0;
        double percentCorrect;
        final int totalQuestions = 5;
        
   
   //Code that all of the answer inputs will be turned to uppercase    
        ans1 = txtQ1answer.getText().toUpperCase();
        ans2 = txtQ2answer.getText().toUpperCase();
        ans3 = txtQ3answer.getText().toUpperCase();
        ans4 = txtQ4answer.getText().toUpperCase();
        ans5 = txtQ5answer.getText().toUpperCase();
       
        //when answer 1 equals B 
        if (ans1.equals("B")){
        //for every correct answer add one to totalCorect
            totalCorrect = totalCorrect + 1;
        //set lblTotalCorrect to the string value of totalCorrect.
            lblTotalCorrect.setText(String.valueOf(totalCorrect));
        //for every question answered add one to numQuestionsAnswered
            numQuestionsAnswered = numQuestionsAnswered + 1;
        //set questionsAnsweredTotal to the string vlaue of numQuestionsAnswered
            questionsAnsweredTotal.setText(String.valueOf(numQuestionsAnswered));
        //set lblQ1answer to output 'Correct!'  
            lblQ1answer.setText("Correct!"); 
        }
        else {
        // set lblQ2answer to output 'incorrect'
            lblQ1answer.setText("Incorrect!");
        //for every incorrect answer add one to the totalIncorrect
            totalIncorrect = totalIncorrect +1 ;
        //set lblTotalIncorrect to the string value of totalincorrect
            lblTotalIncorrect.setText(String.valueOf(totalIncorrect));
        //for every question answered add one to numQuestionsAnswered 
           numQuestionsAnswered = numQuestionsAnswered + 1;
        //set lblQ1answer to output 'Incorrect!'
           questionsAnsweredTotal.setText(String.valueOf(numQuestionsAnswered));
        }
        //When answer two equals 'B' then,
        if (ans2.equals("B")){
            totalCorrect = totalCorrect + 1;
            lblTotalCorrect.setText(String.valueOf(totalCorrect));
            numQuestionsAnswered = numQuestionsAnswered + 1;
            questionsAnsweredTotal.setText(String.valueOf(numQuestionsAnswered));
            lblQ2answer.setText("Correct");
        }
        else { 
            lblQ2answer.setText("Incorrect");
            totalIncorrect = totalIncorrect +1;
            lblTotalIncorrect.setText(String.valueOf(totalIncorrect));
            numQuestionsAnswered = numQuestionsAnswered +1;
            questionsAnsweredTotal.setText(String.valueOf(numQuestionsAnswered));
        }
         if (ans3.equals("B")){
            totalCorrect = totalCorrect + 1;
            lblTotalCorrect.setText(String.valueOf(totalCorrect));
            numQuestionsAnswered = numQuestionsAnswered +1 ;
            questionsAnsweredTotal.setText(String.valueOf(numQuestionsAnswered));
            lblQ3answer.setText("Correct!"); 
        }
        else {
            lblQ3answer.setText("Incorrect!");
            totalIncorrect = totalIncorrect +1 ;
            lblTotalIncorrect.setText(String.valueOf(totalIncorrect));
           numQuestionsAnswered = numQuestionsAnswered + 1;
           questionsAnsweredTotal.setText(String.valueOf(numQuestionsAnswered));
        }
         if (ans4.equals("B")){
            totalCorrect = totalCorrect + 1;
            lblTotalCorrect.setText(String.valueOf(totalCorrect));
            numQuestionsAnswered = numQuestionsAnswered +1 ;
            questionsAnsweredTotal.setText(String.valueOf(numQuestionsAnswered));
            lblQ4answer.setText("Correct!"); 
        }
        else {
            lblQ4answer.setText("Incorrect!");
            totalIncorrect = totalIncorrect +1 ;
            lblTotalIncorrect.setText(String.valueOf(totalIncorrect));
           numQuestionsAnswered = numQuestionsAnswered + 1;
           questionsAnsweredTotal.setText(String.valueOf(numQuestionsAnswered));
         }
         
          if (ans5.equals("B")){
            totalCorrect = totalCorrect + 1;
            lblTotalCorrect.setText(String.valueOf(totalCorrect));
            numQuestionsAnswered = numQuestionsAnswered +1 ;
            questionsAnsweredTotal.setText(String.valueOf(numQuestionsAnswered));
            lblQ5answer.setText("Correct!"); 
        }
        else {
            lblQ5answer.setText("Incorrect!");
            totalIncorrect = totalIncorrect + 1; 
            lblTotalIncorrect.setText(String.valueOf(totalIncorrect));
           numQuestionsAnswered = numQuestionsAnswered + 1;
           questionsAnsweredTotal.setText(String.valueOf(numQuestionsAnswered));
        }
          //percent of questions correct is the value of totalCorrect as a double,
          //divided by the value of totalQuestions as a double, multiplied by 100. 
          percentCorrect = (Double.valueOf(totalCorrect)/Double.valueOf(totalQuestions)*100);
          //set lblPercentCorrect to say the calculated value of percentCorrect as a %.
          lblPercentCorrect.setText(String.valueOf(percentCorrect)+"%");
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultipleChoiceQuizGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCorrectQuestions;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblIncorrectQuestions;
    private javax.swing.JLabel lblNumQuestionsAnswered;
    private javax.swing.JLabel lblPercentCorrect;
    private javax.swing.JLabel lblQ1a;
    private javax.swing.JLabel lblQ1answer;
    private javax.swing.JLabel lblQ1b;
    private javax.swing.JLabel lblQ1c;
    private javax.swing.JLabel lblQ2a;
    private javax.swing.JLabel lblQ2answer;
    private javax.swing.JLabel lblQ2b;
    private javax.swing.JLabel lblQ2c;
    private javax.swing.JLabel lblQ2d;
    private javax.swing.JLabel lblQ3a;
    private javax.swing.JLabel lblQ3answer;
    private javax.swing.JLabel lblQ3b;
    private javax.swing.JLabel lblQ3c;
    private javax.swing.JLabel lblQ3d;
    private javax.swing.JLabel lblQ4a;
    private javax.swing.JLabel lblQ4answer;
    private javax.swing.JLabel lblQ4b;
    private javax.swing.JLabel lblQ4c;
    private javax.swing.JLabel lblQ4d;
    private javax.swing.JLabel lblQ5a;
    private javax.swing.JLabel lblQ5answer;
    private javax.swing.JLabel lblQ5b;
    private javax.swing.JLabel lblQ5c;
    private javax.swing.JLabel lblQ5d;
    private javax.swing.JLabel lblQuestion1;
    private javax.swing.JLabel lblQuestion2;
    private javax.swing.JLabel lblQuestion3;
    private javax.swing.JLabel lblQuestion4;
    private javax.swing.JLabel lblQuestion5;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTotalCorrect;
    private javax.swing.JLabel lblTotalIncorrect;
    private javax.swing.JLabel lblUserPrompt;
    private javax.swing.JLabel questionsAnsweredTotal;
    private javax.swing.JTextField txtQ1answer;
    private javax.swing.JTextField txtQ2answer;
    private javax.swing.JTextField txtQ3answer;
    private javax.swing.JTextField txtQ4answer;
    private javax.swing.JTextField txtQ5answer;
    // End of variables declaration//GEN-END:variables
}
